on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-linux-android, armv7-linux-androideabi]
        include:
          - arch: arm64-v8a
            target: aarch64-linux-android
          - arch: armeabi-v7a
            target: armv7-linux-androideabi

    steps:
      - uses: actions/checkout@v3
      - name: Setup NDK
        run: |
          wget -nv https://dl.google.com/android/repository/android-ndk-r25-linux.zip
          unzip -qo android-ndk-r25-linux.zip
          chmod -R 777 ./android-ndk-r25
          export NDK_HOME="$(pwd)/android-ndk-r25"
          cargo install cargo-ndk

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src
          target: ${{ matrix.target }}

      - name: Build
        run: cargo ndk -t ${{ matrix.arch }} -p 24 -- build --release -j $(nproc)

      - uses: actions/upload-artifact@v3
        with:
          name: cmpr-${{ matrix.arch }}
          path: ./target/${{ matrix.target }}/release/cmpr

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - id: date
        run: echo ::set-output name=date::$(date +'%Y%m%d')

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./cmpr/*
          release_name: cmpr
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          file_glob: true
